[package]
name = "quelle_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
quelle_engine = { path = "../engine" }
quelle_store = { path = "../store" }
quelle_storage = { path = "../storage" }
quelle_export = { path = "../export" }

clap = { version = "4.5.48", features = ["derive"] }
dirs = "5.0"
uuid = { version = "1.0", features = ["v4"] }

tracing.workspace = true
tracing-subscriber.workspace = true
eyre.workspace = true
url.workspace = true
tokio = { version = "1.0", features = ["full"] }
