[package]
name = "extension_scribblehub"
version = "0.1.0"
edition = "2024"

[dependencies]
quelle_extension = { path = "../../crates/extension" }
scraper = { workspace = true }
chrono = { workspace = true }
once_cell = { workspace = true }

[lib]
crate-type = ["cdylib"]
